# https://dart.dev/tools/pub/pubspec
# https://dart.dev/tools/pub/publishing
# https://semver.org/spec/v2.0.0-rc.1.html

name: oracle_object_storage
description: Package para construir os headers de requisições REST API para usar os serviços da Oracle Cloud Object Storage.
version: 0.0.3-dev.1
homepage: https://github.com/Suebersson/oracle_object_storage.git
repository: https://github.com/Suebersson/oracle_object_storage
issue_tracker: https://github.com/Suebersson/oracle_object_storage/issues
documentation: https://pub.dev/documentation/oracle_object_storage/latest/

# Comandos para atulizar o repositório no github
# git init
# git add .
# git commit -m "name commit"
# git remote add origin https://github.com/Suebersson/oracle_object_storage.git
# git pull origin main
# git push -u origin main

environment:
  sdk: ^3.0.0 # ^3.4.3

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

topics:
  - oracle
  - oracle-cloud
  - oracle-object-storage
  - cloud-storage
  - oci

dependencies:
  intl: ^0.19.0
  pointycastle: ^3.9.1
  asn1lib: ^1.5.3

dev_dependencies:
  http: ^1.2.2
  lints: ^4.0.0
  test: ^1.24.0